---
dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-11/run.sh |
  bash
script:
  - wget https://releases.hashicorp.com/packer/1.3.4/packer_1.3.4_linux_amd64.zip -O /tmp/packer.zip
  - wget https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip -O /tmp/terraform.zip
  - wget https://github.com/wata727/tflint/releases/download/v0.7.3/tflint_linux_amd64.zip -O /tmp/tflint.zip
  - pip install ansible-lint --user
  - unzip -o /tmp/packer.zip -d /tmp
  - unzip -o /tmp/terraform.zip -d /tmp
  - unzip -o /tmp/tflint.zip -d /tmp
  - ls -la
  - /tmp/packer validate -var-file=packer/variables.json packer/app.json
  - /tmp/packer validate -var-file=packer/variables.json packer/db.json
  - terraform get terraform/prod
  - terraform init terraform/prod
  - terraform validate terraform/prod
  - /tmp/tflint --deep terraform/prod
  - terraform get terraform/stage
  - terraform init terraform/stage
  - terraform validate terraform/stage
  - /tmp/tflint --deep terraform/stage
  - ansible-lint ansible/playbooks/site.yml

notifications:
  slack:
    rooms:
      secure: VQIG77qGrYTNCqsbs60eVyt9598qGodpugHRYP6Xv0XubxIGaD88bwwVNWIXzC++jW+rO6dVaa4Tl0OcyBJwkUO5lmNT0w12+ZSAYpNWQSj86dTmpgv3pjwGNn4iq7dUumyV6nMJDaxsLyc44Ezk/7hg/Kk4B/NzmdoVWfJYAlfX2fTm3gxLDlIFJXjQv7sKGH2vyUGpM4rzq0Udq2KosIKHtHw+6i4XmQ+ezVm6p466RdD8r5RSEmFnAIF97DFD3oKyYBquCOEVjul8Vsi6SZXqv8htrXMLHl1TvD8CTLYd8v7EJa1U5QxV4i1fd6xEqtoJUQgudr7Iwja0DhbTKOOSQLmuVlcBYybIIb+tjBfUeGYQISsMFhuvC/OFXMxvx1u7dZrVSATuWCOp5ETpC95BY81c6V9hAoD9066lUVtJrZxJHzBRIboSd+PDv1KBoYHuBGDO7zbWqNW07u5m2ouuyiJevxLiHf/a+gaeJ1TniASmRjsW952myx2tSLvcW026kmrYE9/X3yewpFfQ0+JHhvKFNfJoE2M7hb6AdWuNM4s3NP7B3on80zWSMw0lyMaDFmCwsSJbsiMhkoqD7fM14Ii0Wmf1tYx92GrUyvGI1jg7EEd/pLpj55K9hMv3eakYMJcQ+bql4d5e+5M9CjZZXO4+AmWbzhp49gbOSPg=
