---
- name: configure hosts & deploy application
  hosts: all
  gather_facts: False
  vars: 
    mongo_bind_ip: 0.0.0.0
    db_host: 10.132.15.223
  tasks:
    - name: Change mongo config file
      become: true
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      tags: db-tag
      notify: restart mongod

    - name: Add unit file for puma
      become: true
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      tags: app-tag
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/gcp_appUser/db_config
      tags: app-tag

    - name: enable puma
      become: true
      systemd: name=puma enabled=yes
      tags: app-tag

    - name: Fetch the latest version of app code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: '/home/gcp_appUser/reddit'
        version: monolith
      tags: deploy-tag
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: '/home/gcp_appUser/reddit'
      tags: deploy-tag
      

  handlers:
  - name: restart mongod
    become: true
    service: name=mongod state=restarted
    tags: db-tag

  - name: reload puma
    become: true
    systemd: name=puma state=restarted
    tags: app-tag
